name: .NET Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies for main project
        run: dotnet restore TwitchClipPlayer/TwitchClipPlayer.csproj

      - name: Restore dependencies for test project
        run: dotnet restore TwitchClipPlayerTests/TwitchClipPlayerTests.csproj

      - name: Build main project
        run: dotnet build TwitchClipPlayer/TwitchClipPlayer.csproj --no-restore --configuration Release

      - name: Build test project
        run: dotnet build TwitchClipPlayerTests/TwitchClipPlayerTests.csproj --no-restore --configuration Release

      - name: Run tests
        run: dotnet test TwitchClipPlayerTests/TwitchClipPlayerTests.csproj --no-build --verbosity normal --configuration Release
